import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "./QueryProvider";
import Layout from "@/components/layout/Layout";
import { Suspense } from "react";
import { Roboto } from "next/font/google";
import AuthSessionProvider from "./AuthSessionProvider";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased h-screen scrollbar-hide scrollbar-hover`}
      >
        <AuthSessionProvider>
          <QueryProvider>
            <Suspense>
              <Layout>{children}</Layout>
            </Suspense>
          </QueryProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
